name: Update ICS
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'   # 30 分ごと
  permissions:
   contents: write
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch latest ICS
        run: curl -s "$ICAL_URL" -o calendar.ics
        env:
          ICAL_URL: ${{ secrets.ICAL_URL }}
      - name: Commit & Push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add calendar.ics
          git diff --cached --quiet || git commit -m "update $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
          git push
